type:
  size: 2
  signed: true
count:
current_count:                                                # damaged if < count
firing_arc:                                                   # 1-F, 2-FX, 4-Bx, 8-B, 16-360
specials:                                                     # bit vector
  size: 2
  signed: true
ammo:                                                         # valid for missiles only
