planet_transforms:
  climate:
    when: 0
    min: 1
    max: 3
#  gravity:
#    when: 0
#    min: 1
#    max: 1
  mineral_class:
    when: 0
    min: 1
    max: 2
  environment:
    when: 0
    min: 1
    max: 7
    
uninhabitable_stars:
  number_of_planets:
    - 1 1 1 2 1 1 
    - 1 1 2 2 1 1  
    - 1 1 2 2 1 1    
    - 2 1 2 3 1 1     # - Column is spectral class (0-5 blackhole excluded) 
    - 3 2 3 3 2 1     # - Row is a random number 0-9 generated when the star is born. 
    - 3 2 3 4 2 1 
    - 4 3 4 4 2 1 
    - 4 3 4 5 3 1 
    - 5 4 5 5 3 1 
    - 5 4 5 5 4 1
  
randomized_planet:   
  group:
    - 0 0 0 0 1       #Row is star's spectral_class
    - 0 0 1 2 3       #Column is planet's orbit
    - 0 1 2 2 3 
    - 1 2 2 2 3
    - 1 2 3 3 3
    - 0 0 1 2 3
    
  type:
    - 1 1 1 1 1 
    - 4 1 1 1 2       
    - 3 2 1 2 2       
    - 3 3 2 2 2       # - Columns are orbit numbers in star system 
    - 3 3 2 2 2       # - Row is a random number (0-9) 
    - 3 3 3 3 2       # - Each element is the satellite type allowed in that orbit.  As follows: 
    - 3 3 3 3 3       #     1 = Asteroid 
    - 3 3 3 3 3       #     2 = Gas Giant 
    - 3 3 3 3 3       #     3 = Planet 
    - 3 3 3 3 3       #     4 = special
    
  climate: 
    mineral_rich:
      -  0  0  0  0
      - 55 50 15  0
      - 25 25 10 70
      -  5 10 10  0
      -  0  5 10  8
      -  0  0 10  2
      -  0  0 11  0
      -  0  0 11  0
      -  0  0 11  0
      -  0  0  2  0
    average:
      -  0  0  0  0
      - 55 50 15  0
      - 25 25 10 70
      -  5 10 10  0   # Columns are planet's group
      -  0  5 10  8   # Rows are a planet's environment
      -  0  0 10  2   # Values are weighting for that group/environment combination
      -  0  0 11  0
      -  0  0 11  0
      -  0  0 11  0
      -  0  0  2  0
    organic_rich:
      -  0  0  0  0
      - 40 30  8  0
      - 20 20  8 50
      - 25 25 13  0
      -  0 20 13 30
      -  0  0 13  0
      -  0  0 13  0
      -  0  0 13  0
      -  0  0 10  0
      -  0  0  4  0
    
  mineral_class:
    - 2 1 1 1 1 1     
    - 2 1 1 1 1 2 
    - 2 2 1 1 1 2     # Row is a random number (0-9) 
    - 2 2 2 1 1 2     # Column is star class as follows: 
    - 3 2 2 1 2 2     #    0 = Blue 
    - 3 2 2 2 2 2     #    1 = White 
    - 3 3 2 2 2 3     #    2 = Yellow 
    - 3 3 3 2 2 3     #    3 = Orange 
    - 4 3 3 2 2 3     #    4 = Red  
    - 4 4 4 3 2 4     #    5 = Brown
    
  size:
    - 0 
    - 3             
    - 7               # numbers are rolled in sequence, starting with tiny.  one field must be 10
    - 9
    - 10
    
  gravity: 
    - 0 0 0 1 1 
    - 0 0 1 1 1    
    - 0 1 1 1 2       #- Column is planet size 
    - 1 1 1 2 2       #- Row is planet mineral class 
    - 1 1 2 2 2

  
