home_stars:
  offset_from_center: 480

home_star_cluster:
  extra_stars: 3
  mirror_stars: true
  offset_from_home_star: 80
   

center_stars:
  outer_ring_guarded_by_monsters: false
  stars_per_ring:
    - 4
    - 4
    - 8
  offset_per_ring:
    - 75
    - 125
    - 200
  angular_offset_per_ring:
    - Math::PI/4
    - 0
    - 0
  star_size_per_ring:
    - 1
    - 2
    - 2

orion: true

block_travel: true
  
