rings: 
  offset:
    - 0.2
    - 0.275
    - 0.35
    - 0.425
  stars:
    - 16
    - home
    - 16
    - 24
  favor_habitable_stars: true

remaining_stars:
  action: move #options are remove, leave_in_place, move
  replace_with_black_holes: true
  offset: 0.1 #only required if action is 'move'
  
wormholes:
  keep_existing: false
  add_inner_wormholes: true
  