number_of_planets:
  - 1 1 1 2 1 1 
  - 1 1 2 2 1 1  
  - 1 1 2 2 1 1    
  - 2 1 2 3 1 1     # - Column is spectral class (0-5 blackhole excluded) 
  - 3 2 3 3 2 1     # - Row is a random number 0-9 generated when the star is born. 
  - 3 2 3 4 2 1 
  - 4 3 4 4 2 1 
  - 4 3 4 5 3 1 
  - 5 4 5 5 3 1 
  - 5 4 5 5 4 1
  


  
